development:
  adapter: postgresql
  host: localhost
  database: sample-app-dev

test: &test
  adapter: postgresql
  host: localhost
  database: sample-app-test

production:
  adapter: postgresql
  host: localhost
  username: user
  database: sample-app-production

cucumber:
  <<: *test